contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #virba_sniff channel"
    url: https://nfcore.slack.com/channels/virba_sniff
    about: Discussion about the glab/virba_sniff pipeline
